### ISSUE TITLE
Automated contributors List

### ISSUE THREAD

**Issue by flexbox** [MatthysDucrocq/projetflutter#12]
As a Developer
I can automate the contributor's list
So that I can focus on shipping features

--

Example
https://github.com/flexbox/inspiration#contributors-

- [ ] Delete contributors on the README
- [ ] Add https://allcontributors.org/
- [ ] Comment in this [issue with these params](https://allcontributors.org/docs/en/bot/usage):
```
@all-contributors please add @<username> for <contributions>
```

**Comment by MatthysDev** [comment]
@all-contributors please add @<username> for <contributions>

**Comment by MatthysDev** [comment]
@all-contributors please add @MatthysDucrocq @Corentyn @rayles59 @Jcbutnotjesus  for test,dev and design
